# RUN docker-compose up --build -d

version: "2.8"

services:
  apponesql:
    build: .
    depends_on:
      - postgres
    ports:
      - 3002:8002
    command:
      - "uvicorn"
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8002"

    environment:
      # DB
      - TOKEN_SECRET=663559295b77455ceb6623fb398e8e831ec022e81087515ede29f6ddf3e1f336
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=database
      - POSTGRES_PASSWORD=database
      - POSTGRES_DB=database
        # JWT
      - SECRET_KEY=7c0d5815b3d6604a7f7f43c80ad83fe25df5f0f850cec1da0e7a22bd2c8705b5
      - ALGORITHM=HS256
      - TOKEN_EXPIRE_MINUTES=120
        # AUTH
      - ISSUER='https://dev-hxud9tl6.us.auth0.com/'
      - API_AUDIENCE='https://app-one-sql.herokuapp.com/'
      - DOMAIN_AUTH0='dev-hxud9tl6.us.auth0.com'
      - ALGORITHM_AUTH0='RS256'

  postgres:
    image: postgres:11.5
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

    # Commit this ports for close access to the database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=database
      - POSTGRES_PASSWORD=database

volumes:
  postgres-db:
